### ISSUE TITLE
time cost of 7b model training compared to AdamW

### ISSUE THREAD

**Issue by dawnranger** [OpenLMLab/LOMO#2]
Does it means LOMO is 11 times faster than AdamW? 

![image](https://github.com/OpenLMLab/LOMO/assets/10653991/5a8116c3-f9f2-4e8c-b3a9-ef4ace9dff70)

**Comment by KaiLv69** [comment]
Our experiments focus on fine-tuning large language models on consumer GPUs like RTX 3090. The testing under these conditions is indeed as stated (using the 7b model on RTX 3090 GPUs, with a batch size of 1024 tokens and parallel strategy of ZeRO-3). As mentioned in the paper, this is because LOMO does not require inter-GPU communication. In the scenario where model parallelism is necessary for LOMO (13b model), LOMO is not significantly faster than SGD by a factor of 11 when inter-GPU communication is required.
Regarding the 13b/30b/65b model, we cannot claim that LOMO is 11 times faster than AdamW because these model cannot be trained with AdamW using 8 RTX 3090 GPUs.

**Comment by Amshaker** [comment]
@KaiLv69 ,
Could you please release the code of LOMO to reproduce & measure the training time on different GPUs?

**Comment by KaiLv69** [comment]
Based on the information provided, we consider this issue resolved. If you have any further questions or concerns, please reopen this issue and provide additional details.
